server:
  port: 8082

spring:
  application:
    name: song-service
  datasource:
    url: jdbc:postgresql://localhost:5434/songdb
    username: song
    password: song123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true