server:
  port: 9000

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service-route
          uri: ${target.user-service.url}
          predicates:
            - Path=/api/users/**
        - id: monolith-route
          uri: ${target.monolith.url}
          predicates:
            - Path=/**

feature:
  toggle:
    user-service-enabled: true

target:
  monolith:
    url: http://localhost:8080
  user-service:
    url: http://localhost:8081

logging:
  level:
    org.springframework.cloud.gateway: DEBUG